server:
  port: 8082
spring:
  application:
    name: asset
  datasource:
    password: password
    url: jdbc:postgresql://host.docker.internal:5433/assetSummary
    username: postgres
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true
  flyway:
    baselineOnMigrate: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.0.2:8761/eureka