server:
  port: 8082

spring:
  application:
    name: asset
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true
  flyway:
    baselineOnMigrate: true
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://host.docker.internal:8888

