ALTER TABLE ASSET ADD COLUMN BALANCE DOUBLE PRECISION not null DEFAULT 0;
ALTER TABLE ASSET ADD COLUMN CREATED_DATE TIMESTAMP DEFAULT NOW();
ALTER TABLE ASSET ADD COLUMN UPDATED_DATE TIMESTAMP DEFAULT NOW();